import { WinnersOrderParameter, WinnersSortParameter } from '@ts-enums';

export default {
  API_URL: 'http://localhost:3000/',
  DEFAULT_WINNERS_PER_PAGE: 10,
  DEFAULT_WINNERS_PAGE_NUMBER: 1,
  DEFAULT_WINNERS_SORT_BY: WinnersSortParameter.TIME,
  DEFAULT_WINNERS_SORT_ORDER: WinnersOrderParameter.ASC,
  DEFAULT_CARS_PER_PAGE: 7,
  DEFAULT_CARS_PAGE_NUMBER: 1,
  BULK_CARS_NUMBER: 100,
  ADJECTIVES: [
    'Savage',
    'Mighty',
    'Thunderous',
    'Infernal',
    'Ruthless',
    'Vicious',
    'Ironclad',
    'Fearsome',
    'Relentless',
    'Brutal',
    'Ferocious',
    'Unstoppable',
    'Demonic',
    'Colossal',
    'Wrathful',
    'Hellish',
    'Imperial',
    'Furious',
    'Bloodthirsty',
    'Unbreakable',
    'Destructive',
    'Immortal',
    'Doomed',
    'Monstrous',
    'Incredible',
    'Vengeful',
    'Cruel',
    'Devastating',
    'Invincible',
    'Dark',
    'Exiled',
  ] as const,
  NOUNS: [
    'Beast',
    'Crusher',
    'Reaper',
    'Warlord',
    'Titan',
    'Fury',
    'Dominator',
    'Plow',
    'Harvester',
    'Ripper',
    'Juggernaut',
    'Annihilator',
    'Destroyer',
    'Gladiator',
    'Conqueror',
    'Nightmare',
    'Crusader',
    'Herald',
    'Slayer',
    'Champion',
    'DeathBringer',
    'Drill',
    'Cutter',
    'Mower',
    'Shredder',
    'Grinder',
    'Slicer',
    'Saw',
    'Scythe',
    'Fiend',
    'Demon',
    'Warrior',
    'Despoiler',
    'Desecrator',
    'Defiler',
    'Devourer',
    'Avenger',
  ] as const,
} as const;
